recipe: default.v1
language: zh

pipeline:
  #	- name: "custom_components.bert_vectors_featurizer.BertVectorsFeaturizer"
  #		ip: "192.168.15.57"
  #		port: 5555
  #		port_out: 5556
  #		show_server_config: True
  #		timeout: 5000
  #		output_fmt: "ndarray"
  #		check_version: True
  #		identity: None,
  #		batch_size: 128
# 方案一
  - name: JiebaTokenizer
    dictionary_path: "data/dict"
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "bert-base-chinese"
  - name: DIETClassifier
    constrain_similarities: True
    epochs: 100
    learning_rate: 0.001
  - name: RegexEntityExtractor
  - name: EntitySynonymMapper
  - name: ResponseSelector
  - name: FallbackClassifier
    threshold: 0.6
    ambiguity_threshold: 0.1

# 方案二
#  - name: MitieNLP
#    model: "data/total_word_feature_extractor_zh.dat"
#  - name: JiebaTokenizer
#    dictionary_path: "data/dict"
#  - name: RegexFeaturizer
#    number_additional_patterns: 10
#  - name: MitieFeaturizer
#  - name: DIETClassifier
#    constrain_similarities: True
#    epochs: 100
#    learning_rate: 0.001
#  - name: RegexEntityExtractor
#  - name: EntitySynonymMapper

#   方案三
#  - name: "MitieNLP"
#    model: "data/total_word_feature_extractor_zh.dat"
#  - name: "JiebaTokenizer"
#    dictionary_path: "data/dict"
#  - name: "MitieEntityExtractor"
#  - name: "EntitySynonymMapper"
#  - name: "RegexFeaturizer"
#  - name: "MitieFeaturizer"
#  - name: "SklearnIntentClassifier"
#  - name: "CRFEntityExtractor"
#  - name: "DIETClassifier"
#    epochs: 100
#  - name: "EntitySynonymMapper"



# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
#    core_fallback_threshold: 0.3
#    core_fallback_action_name: action_default_fallback
#    enable_fallback_prediction: true
